### ISSUE TITLE
mean and std for input 

### ISSUE THREAD

**Issue by Bezdarnost** [gau-nernst/timm-face#2]
Thank you very much for awesome work!

Did you use mean=[0.5, 0.5, 0.5] and std=[0.5, 0.5, 0.5] standardization for all inputs in the process of training?

**Comment by gau-nernst** [comment]
Yes
https://github.com/gau-nernst/timm-face/blob/85c61d8b0e53770b5b0c74ba60fd919654399d4a/data.py#L156
